version: 2
updates:

  # Group: GitHub Actions
  - group-name: "GitHub Actions Dependencies"
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Group: npm
  - group-name: "npm Dependencies"
    package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10